generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: ordwaylabs.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 21 12:29:03 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: ordwaylabs.stoplight.io
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  6 22:17:08 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: api.ordwaylabs.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan  6 23:59:59 2027 GMT
  hsts: null
domains:
- domain: ordwaylabs.com
  dnssec: false
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: quarantine
- domain: stoplight.io
  dnssec: false
  caa:
  - 0 issuewild "letsencrypt.org"
  - 0 issuewild "pki.goog; cansignhttpexchanges=yes"
  - 0 issuewild "ssl.com"
  - 0 iodef "mailto:devops@stoplight.io"
  - 0 issue "cloudflare.com"
  - 0 issue "comodoca.com"
  spf: true
  dmarc: true
  dmarc_policy: reject
